<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251220000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create records table based on legacy historial table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, patient_id INT NOT NULL, created_at DATE NOT NULL, consultation_reason TEXT DEFAULT NULL, onset TEXT DEFAULT NULL, radiology_tests TEXT DEFAULT NULL, evolution TEXT DEFAULT NULL, current_situation TEXT DEFAULT NULL, sick_leave BOOLEAN DEFAULT NULL, physiotherapy_treatment TEXT NOT NULL, medical_treatment TEXT DEFAULT NULL, home_treatment TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RECORDS_PATIENT_ID ON records (patient_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE records');
    }
}
