<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251221141421 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_appointments_starts_at');
        $this->addSql('DROP INDEX idx_appointments_user_id');
        $this->addSql('DROP INDEX idx_appointments_ends_at');
        $this->addSql('ALTER TABLE appointments ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE appointments ALTER created_at DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN appointments.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN appointments.all_day IS \'\'');
        $this->addSql('COMMENT ON COLUMN appointments.starts_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN appointments.ends_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN appointments.custom_fields IS \'\'');
        $this->addSql('COMMENT ON COLUMN appointments.notes IS \'\'');
        $this->addSql('DROP INDEX idx_customers_patient_id');
        $this->addSql('ALTER TABLE records ADD CONSTRAINT FK_9C9D58466B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_records_patient_id RENAME TO IDX_9C9D58466B899279');
        $this->addSql('ALTER INDEX uniq_identifier_email RENAME TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointments ALTER id SET DEFAULT nextval(\'appointments_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE appointments ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE appointments ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('COMMENT ON COLUMN appointments.user_id IS \'Reference to the user who owns this appointment\'');
        $this->addSql('COMMENT ON COLUMN appointments.all_day IS \'Whether the appointment spans the entire day\'');
        $this->addSql('COMMENT ON COLUMN appointments.starts_at IS \'Appointment start date and time\'');
        $this->addSql('COMMENT ON COLUMN appointments.ends_at IS \'Appointment end date and time\'');
        $this->addSql('COMMENT ON COLUMN appointments.custom_fields IS \'Additional custom fields stored as JSON\'');
        $this->addSql('COMMENT ON COLUMN appointments.notes IS \'Additional notes or comments about the appointment\'');
        $this->addSql('CREATE INDEX idx_appointments_starts_at ON appointments (starts_at)');
        $this->addSql('CREATE INDEX idx_appointments_user_id ON appointments (user_id)');
        $this->addSql('CREATE INDEX idx_appointments_ends_at ON appointments (ends_at)');
        $this->addSql('CREATE INDEX idx_customers_patient_id ON customers (patient_id)');
        $this->addSql('ALTER TABLE records DROP CONSTRAINT FK_9C9D58466B899279');
        $this->addSql('ALTER INDEX idx_9c9d58466b899279 RENAME TO idx_records_patient_id');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO uniq_identifier_email');
    }
}
