<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251222211649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, all_day BOOLEAN DEFAULT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, type VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, patient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A41727A6B899279 ON appointments (patient_id)');
        $this->addSql('CREATE TABLE counters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, value TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_451114915E237E06 ON counters (name)');
        $this->addSql('CREATE TABLE customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, patient_id INT DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, tax_id VARCHAR(20) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, billing_address TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE invoices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(20) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount DOUBLE PRECISION NOT NULL, name VARCHAR(50) NOT NULL, phone VARCHAR(50) DEFAULT NULL, address VARCHAR(250) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, tax_id VARCHAR(15) DEFAULT NULL, created_at DATE NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2F2F959395C3F3 ON invoices (customer_id)');
        $this->addSql('CREATE TABLE invoice_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_id INT NOT NULL, concept VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, quantity INT NOT NULL, price DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_72DBDC232989F1FD ON invoice_lines (invoice_id)');
        $this->addSql('CREATE TABLE patients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(100) NOT NULL, date_of_birth DATE DEFAULT NULL, identity_document VARCHAR(15) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, created_at DATE NOT NULL, address VARCHAR(250) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, profession VARCHAR(250) DEFAULT NULL, sports_activity VARCHAR(250) DEFAULT NULL, notes VARCHAR(250) DEFAULT NULL, rate VARCHAR(250) DEFAULT NULL, allergies VARCHAR(250) DEFAULT NULL, medication VARCHAR(250) DEFAULT NULL, systemic_diseases VARCHAR(250) DEFAULT NULL, surgeries VARCHAR(250) DEFAULT NULL, accidents VARCHAR(250) DEFAULT NULL, injuries VARCHAR(250) DEFAULT NULL, bruxism VARCHAR(250) DEFAULT NULL, insoles VARCHAR(250) DEFAULT NULL, others VARCHAR(250) DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at DATE NOT NULL, consultation_reason TEXT DEFAULT NULL, onset TEXT DEFAULT NULL, radiology_tests TEXT DEFAULT NULL, evolution TEXT DEFAULT NULL, current_situation TEXT DEFAULT NULL, sick_leave BOOLEAN DEFAULT NULL, physiotherapy_treatment TEXT NOT NULL, medical_treatment TEXT DEFAULT NULL, home_treatment TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, patient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C9D58466B899279 ON records (patient_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE appointments ADD CONSTRAINT FK_6A41727A6B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE records ADD CONSTRAINT FK_9C9D58466B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoices ADD CONSTRAINT FK_6A2F2F959395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_lines ADD CONSTRAINT FK_72DBDC232989F1FD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointments DROP CONSTRAINT FK_6A41727A6B899279');
        $this->addSql('ALTER TABLE records DROP CONSTRAINT FK_9C9D58466B899279');
        $this->addSql('ALTER TABLE invoices DROP CONSTRAINT FK_6A2F2F959395C3F3');
        $this->addSql('ALTER TABLE invoice_lines DROP CONSTRAINT FK_72DBDC232989F1FD');
        $this->addSql('DROP TABLE appointments');
        $this->addSql('DROP TABLE counters');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE invoice_lines');
        $this->addSql('DROP TABLE patients');
        $this->addSql('DROP TABLE records');
        $this->addSql('DROP TABLE users');
    }
}
