<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251220000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create patients table based on legacy paciente table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(100) NOT NULL, date_of_birth DATE DEFAULT NULL, identity_document VARCHAR(15) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, created_at DATE NOT NULL, address VARCHAR(250) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, profession VARCHAR(250) DEFAULT NULL, sports_activity VARCHAR(250) DEFAULT NULL, notes VARCHAR(250) DEFAULT NULL, rate VARCHAR(250) DEFAULT NULL, allergies VARCHAR(250) DEFAULT NULL, medication VARCHAR(250) DEFAULT NULL, systemic_diseases VARCHAR(250) DEFAULT NULL, surgeries VARCHAR(250) DEFAULT NULL, accidents VARCHAR(250) DEFAULT NULL, injuries VARCHAR(250) DEFAULT NULL, bruxism VARCHAR(250) DEFAULT NULL, insoles VARCHAR(250) DEFAULT NULL, others VARCHAR(250) DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE patients');
    }
}
